server:
  port: 8088
spring:
  profiles:
    active: gitee
  application:
    name: xtp-api-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.104:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
#    服务失效时间
    lease-expiration-duration-in-seconds: 90
#    服务续约任务的调用时间间隔
    lease-renewal-interval-in-seconds: 30