server:
  port: 8051
spring:
  profiles:
    active: test
  application:
    name: xtp-api-service
# MyBatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
  type-aliases-package: cn.xtits.xtp.entity
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
#    服务失效时间
    lease-expiration-duration-in-seconds: 90
#    服务续约任务的调用时间间隔
    lease-renewal-interval-in-seconds: 30
