server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://192.168.2.102:3306/git-xtp
    username: hail
    password: hail
    driver-class-name: com.mysql.jdbc.Driver

# MyBatis
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis-config.xml
    type-aliases-package: cn.xtits.xtp.entity

REST_XTP_URL: http://139.196.125.197/xtp-api
APP_TOKEN: CJzdWIiOiJ7XCJ1c2VySDkwMTUeyJhbGciOiJI