spring:
  datasource:
    url: jdbc:mysql://139.196.125.197:3306/git-xtp?useUnicode=true&characterEncoding=UTF-8
    username: git-xtp
    password: 'git-xtp'
    driver-class-name: com.mysql.jdbc.Driver
# MyBatis
mybatis:
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis-config.xml
    type-aliases-package: cn.xtits.iformula.entity

REST_XTP_URL: http://localhost:8088/xtp-api
APP_TOKEN: CJzdWIiOiJ7XCJ1c2VySDkwMTUeyJhbGciOiJI
TTL_MILLIS: 31536000000
logging:
  level: debug
