spring:
  datasource:
    url: jdbc:mysql://139.196.125.197:3306/git-xtp?useUnicode=true&characterEncoding=UTF-8
    username: git-xtp
    password: 'git-xtp'
    driver-class-name: com.mysql.jdbc.Driver

REST_XTP_URL: http://localhost:5555/xtp-api
APP_TOKEN: CJzdWIiOiJ7XCJ1c2VySDkwMTUeyJhbGciOiJI
TTL_MILLIS: 31536000000
logging:
  level: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://139.196.125.197:8761/eureka/
