#server:
#  context-path: /xtp-api
spring:
  datasource:
    url: jdbc:mysql://119.37.194.4:11161/ie-xtp?useUnicode=true&characterEncoding=UTF-8
    username: js
    password: 'Gd81dwPBnuoKYFzd'
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.2.111
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
    timeout: 0
      #彩色output
REST_XTP_URL: http://localhost:5555/xtp-api
APP_TOKEN: CJzdWIiOiJ7XCJ1c2VySDkwMTUeyJhbGciOiJI
TTL_MILLIS: 31536000000
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.103:8761/eureka/

