package cn.xtits.xtp.entity;

import java.io.Serializable;

public class AppFavorite implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appfavorite.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appfavorite.AppId
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appfavorite.MenuId
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appfavorite.Id
     *
     * @return the value of appfavorite.Id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appfavorite.Id
     *
     * @param id the value for appfavorite.Id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appfavorite.AppId
     *
     * @return the value of appfavorite.AppId
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appfavorite.AppId
     *
     * @param appId the value for appfavorite.AppId
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appfavorite.MenuId
     *
     * @return the value of appfavorite.MenuId
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appfavorite.MenuId
     *
     * @param menuId the value for appfavorite.MenuId
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}