package cn.xtits.xtp.entity;

import java.io.Serializable;
import java.util.Date;

public class Dict implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.Tpe
     *
     * @mbg.generated
     */
    private String tpe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.Key
     *
     * @mbg.generated
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.Value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.CreateDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.Id
     *
     * @return the value of dict.Id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.Id
     *
     * @param id the value for dict.Id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.Tpe
     *
     * @return the value of dict.Tpe
     * @mbg.generated
     */
    public String getTpe() {
        return tpe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.Tpe
     *
     * @param tpe the value for dict.Tpe
     * @mbg.generated
     */
    public void setTpe(String tpe) {
        this.tpe = tpe == null ? null : tpe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.Key
     *
     * @return the value of dict.Key
     * @mbg.generated
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.Key
     *
     * @param key the value for dict.Key
     * @mbg.generated
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.Value
     *
     * @return the value of dict.Value
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.Value
     *
     * @param value the value for dict.Value
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.CreateDate
     *
     * @return the value of dict.CreateDate
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.CreateDate
     *
     * @param createDate the value for dict.CreateDate
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}