package cn.xtits.xtp.entity;

import java.io.Serializable;

public class Log implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.Type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.Centent
     *
     * @mbg.generated
     */
    private String centent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.UserId
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.UserName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.CreateDate
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.IP
     *
     * @mbg.generated
     */
    private String IP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.Id
     *
     * @return the value of log.Id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.Id
     *
     * @param id the value for log.Id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.Type
     *
     * @return the value of log.Type
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.Type
     *
     * @param type the value for log.Type
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.Centent
     *
     * @return the value of log.Centent
     * @mbg.generated
     */
    public String getCentent() {
        return centent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.Centent
     *
     * @param centent the value for log.Centent
     * @mbg.generated
     */
    public void setCentent(String centent) {
        this.centent = centent == null ? null : centent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.UserId
     *
     * @return the value of log.UserId
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.UserId
     *
     * @param userId the value for log.UserId
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.UserName
     *
     * @return the value of log.UserName
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.UserName
     *
     * @param userName the value for log.UserName
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.CreateDate
     *
     * @return the value of log.CreateDate
     * @mbg.generated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.CreateDate
     *
     * @param createDate the value for log.CreateDate
     * @mbg.generated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.IP
     *
     * @return the value of log.IP
     * @mbg.generated
     */
    public String getIP() {
        return IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.IP
     *
     * @param IP the value for log.IP
     * @mbg.generated
     */
    public void setIP(String IP) {
        this.IP = IP == null ? null : IP.trim();
    }
}