package cn.xtits.xtp.entity;

import java.io.Serializable;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.AppId
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.URL
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ParentId
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ParentFlag
     *
     * @mbg.generated
     */
    private Boolean parentFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.DisplayFlag
     *
     * @mbg.generated
     */
    private Boolean displayFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.DeleteFlag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.Type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.EnableFlag
     *
     * @mbg.generated
     */
    private Boolean enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Id
     *
     * @return the value of menu.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Id
     *
     * @param id the value for menu.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.AppId
     *
     * @return the value of menu.AppId
     *
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.AppId
     *
     * @param appId the value for menu.AppId
     *
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Code
     *
     * @return the value of menu.Code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Code
     *
     * @param code the value for menu.Code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Name
     *
     * @return the value of menu.Name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Name
     *
     * @param name the value for menu.Name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.URL
     *
     * @return the value of menu.URL
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.URL
     *
     * @param url the value for menu.URL
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ParentId
     *
     * @return the value of menu.ParentId
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ParentId
     *
     * @param parentId the value for menu.ParentId
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Icon
     *
     * @return the value of menu.Icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Icon
     *
     * @param icon the value for menu.Icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ParentFlag
     *
     * @return the value of menu.ParentFlag
     *
     * @mbg.generated
     */
    public Boolean getParentFlag() {
        return parentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ParentFlag
     *
     * @param parentFlag the value for menu.ParentFlag
     *
     * @mbg.generated
     */
    public void setParentFlag(Boolean parentFlag) {
        this.parentFlag = parentFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.DisplayFlag
     *
     * @return the value of menu.DisplayFlag
     *
     * @mbg.generated
     */
    public Boolean getDisplayFlag() {
        return displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.DisplayFlag
     *
     * @param displayFlag the value for menu.DisplayFlag
     *
     * @mbg.generated
     */
    public void setDisplayFlag(Boolean displayFlag) {
        this.displayFlag = displayFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Sort
     *
     * @return the value of menu.Sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Sort
     *
     * @param sort the value for menu.Sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.DeleteFlag
     *
     * @return the value of menu.DeleteFlag
     *
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.DeleteFlag
     *
     * @param deleteFlag the value for menu.DeleteFlag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.Type
     *
     * @return the value of menu.Type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.Type
     *
     * @param type the value for menu.Type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.EnableFlag
     *
     * @return the value of menu.EnableFlag
     *
     * @mbg.generated
     */
    public Boolean getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.EnableFlag
     *
     * @param enableFlag the value for menu.EnableFlag
     *
     * @mbg.generated
     */
    public void setEnableFlag(Boolean enableFlag) {
        this.enableFlag = enableFlag;
    }
}