package cn.xtits.xtp.entity;

import java.io.Serializable;
import java.util.Date;

public class Organize implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.AppId
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.ParentId
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.FullName
     *
     * @mbg.generated
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Category
     *
     * @mbg.generated
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.OuterPhone
     *
     * @mbg.generated
     */
    private String outerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.InnerPhone
     *
     * @mbg.generated
     */
    private String innerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Postalcode
     *
     * @mbg.generated
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Web
     *
     * @mbg.generated
     */
    private String web;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Manager
     *
     * @mbg.generated
     */
    private String manager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.AssistantManager
     *
     * @mbg.generated
     */
    private String assistantManager;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.InnerOrganizeFlag
     *
     * @mbg.generated
     */
    private Boolean innerOrganizeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.Description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.EnableFlag
     *
     * @mbg.generated
     */
    private Boolean enableFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.CreateUserID
     *
     * @mbg.generated
     */
    private String createUserID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organize.ModifyDate
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organize
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Id
     *
     * @return the value of organize.Id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Id
     *
     * @param id the value for organize.Id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.AppId
     *
     * @return the value of organize.AppId
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.AppId
     *
     * @param appId the value for organize.AppId
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Code
     *
     * @return the value of organize.Code
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Code
     *
     * @param code the value for organize.Code
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.ParentId
     *
     * @return the value of organize.ParentId
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.ParentId
     *
     * @param parentId the value for organize.ParentId
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.FullName
     *
     * @return the value of organize.FullName
     * @mbg.generated
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.FullName
     *
     * @param fullName the value for organize.FullName
     * @mbg.generated
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Category
     *
     * @return the value of organize.Category
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Category
     *
     * @param category the value for organize.Category
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.OuterPhone
     *
     * @return the value of organize.OuterPhone
     * @mbg.generated
     */
    public String getOuterPhone() {
        return outerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.OuterPhone
     *
     * @param outerPhone the value for organize.OuterPhone
     * @mbg.generated
     */
    public void setOuterPhone(String outerPhone) {
        this.outerPhone = outerPhone == null ? null : outerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.InnerPhone
     *
     * @return the value of organize.InnerPhone
     * @mbg.generated
     */
    public String getInnerPhone() {
        return innerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.InnerPhone
     *
     * @param innerPhone the value for organize.InnerPhone
     * @mbg.generated
     */
    public void setInnerPhone(String innerPhone) {
        this.innerPhone = innerPhone == null ? null : innerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Fax
     *
     * @return the value of organize.Fax
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Fax
     *
     * @param fax the value for organize.Fax
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Postalcode
     *
     * @return the value of organize.Postalcode
     * @mbg.generated
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Postalcode
     *
     * @param postalcode the value for organize.Postalcode
     * @mbg.generated
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Address
     *
     * @return the value of organize.Address
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Address
     *
     * @param address the value for organize.Address
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Web
     *
     * @return the value of organize.Web
     * @mbg.generated
     */
    public String getWeb() {
        return web;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Web
     *
     * @param web the value for organize.Web
     * @mbg.generated
     */
    public void setWeb(String web) {
        this.web = web == null ? null : web.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Manager
     *
     * @return the value of organize.Manager
     * @mbg.generated
     */
    public String getManager() {
        return manager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Manager
     *
     * @param manager the value for organize.Manager
     * @mbg.generated
     */
    public void setManager(String manager) {
        this.manager = manager == null ? null : manager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.AssistantManager
     *
     * @return the value of organize.AssistantManager
     * @mbg.generated
     */
    public String getAssistantManager() {
        return assistantManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.AssistantManager
     *
     * @param assistantManager the value for organize.AssistantManager
     * @mbg.generated
     */
    public void setAssistantManager(String assistantManager) {
        this.assistantManager = assistantManager == null ? null : assistantManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.InnerOrganizeFlag
     *
     * @return the value of organize.InnerOrganizeFlag
     * @mbg.generated
     */
    public Boolean getInnerOrganizeFlag() {
        return innerOrganizeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.InnerOrganizeFlag
     *
     * @param innerOrganizeFlag the value for organize.InnerOrganizeFlag
     * @mbg.generated
     */
    public void setInnerOrganizeFlag(Boolean innerOrganizeFlag) {
        this.innerOrganizeFlag = innerOrganizeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Sort
     *
     * @return the value of organize.Sort
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Sort
     *
     * @param sort the value for organize.Sort
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.Description
     *
     * @return the value of organize.Description
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.Description
     *
     * @param description the value for organize.Description
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.EnableFlag
     *
     * @return the value of organize.EnableFlag
     * @mbg.generated
     */
    public Boolean getEnableFlag() {
        return enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.EnableFlag
     *
     * @param enableFlag the value for organize.EnableFlag
     * @mbg.generated
     */
    public void setEnableFlag(Boolean enableFlag) {
        this.enableFlag = enableFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.CreateUserID
     *
     * @return the value of organize.CreateUserID
     * @mbg.generated
     */
    public String getCreateUserID() {
        return createUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.CreateUserID
     *
     * @param createUserID the value for organize.CreateUserID
     * @mbg.generated
     */
    public void setCreateUserID(String createUserID) {
        this.createUserID = createUserID == null ? null : createUserID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organize.ModifyDate
     *
     * @return the value of organize.ModifyDate
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organize.ModifyDate
     *
     * @param modifyDate the value for organize.ModifyDate
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }
}