package cn.xtits.xtp.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.AppUserId
     *
     * @mbg.generated
     */
    private Integer appUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.AppId
     *
     * @mbg.generated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.OrganizeId
     *
     * @mbg.generated
     */
    private Integer organizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.OrganizeIdName
     *
     * @mbg.generated
     */
    private String organizeIdName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Account
     *
     * @mbg.generated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.QQ
     *
     * @mbg.generated
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CreateDate
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ModifyDate
     *
     * @mbg.generated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DeleteFlag
     *
     * @mbg.generated
     */
    private Boolean deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.groupId
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Id
     *
     * @return the value of user.Id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Id
     *
     * @param id the value for user.Id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.AppUserId
     *
     * @return the value of user.AppUserId
     * @mbg.generated
     */
    public Integer getAppUserId() {
        return appUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.AppUserId
     *
     * @param appUserId the value for user.AppUserId
     * @mbg.generated
     */
    public void setAppUserId(Integer appUserId) {
        this.appUserId = appUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.AppId
     *
     * @return the value of user.AppId
     * @mbg.generated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.AppId
     *
     * @param appId the value for user.AppId
     * @mbg.generated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.OrganizeId
     *
     * @return the value of user.OrganizeId
     * @mbg.generated
     */
    public Integer getOrganizeId() {
        return organizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.OrganizeId
     *
     * @param organizeId the value for user.OrganizeId
     * @mbg.generated
     */
    public void setOrganizeId(Integer organizeId) {
        this.organizeId = organizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.OrganizeIdName
     *
     * @return the value of user.OrganizeIdName
     * @mbg.generated
     */
    public String getOrganizeIdName() {
        return organizeIdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.OrganizeIdName
     *
     * @param organizeIdName the value for user.OrganizeIdName
     * @mbg.generated
     */
    public void setOrganizeIdName(String organizeIdName) {
        this.organizeIdName = organizeIdName == null ? null : organizeIdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Account
     *
     * @return the value of user.Account
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Account
     *
     * @param account the value for user.Account
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Name
     *
     * @return the value of user.Name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Name
     *
     * @param name the value for user.Name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Mail
     *
     * @return the value of user.Mail
     * @mbg.generated
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Mail
     *
     * @param mail the value for user.Mail
     * @mbg.generated
     */
    public void setMail(String mail) {
        this.mail = mail == null ? null : mail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Phone
     *
     * @return the value of user.Phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Phone
     *
     * @param phone the value for user.Phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.QQ
     *
     * @return the value of user.QQ
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.QQ
     *
     * @param qq the value for user.QQ
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CreateDate
     *
     * @return the value of user.CreateDate
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CreateDate
     *
     * @param createDate the value for user.CreateDate
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ModifyDate
     *
     * @return the value of user.ModifyDate
     * @mbg.generated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ModifyDate
     *
     * @param modifyDate the value for user.ModifyDate
     * @mbg.generated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DeleteFlag
     *
     * @return the value of user.DeleteFlag
     * @mbg.generated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DeleteFlag
     *
     * @param deleteFlag the value for user.DeleteFlag
     * @mbg.generated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.groupId
     *
     * @return the value of user.groupId
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.groupId
     *
     * @param groupId the value for user.groupId
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}