package cn.xtits.xtp.mapper;

import cn.xtits.xtp.entity.AppFavorite;
import cn.xtits.xtp.entity.AppFavoriteExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AppFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    long countByExample(AppFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    int insert(AppFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    int insertSelective(AppFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    List<AppFavorite> selectByExample(AppFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    AppFavorite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppFavorite record, @Param("example") AppFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppFavorite record, @Param("example") AppFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appfavorite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppFavorite record);
}