package cn.xtits.xtp.mapper;

import cn.xtits.xtp.entity.MenuOperation;
import cn.xtits.xtp.entity.MenuOperationExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MenuOperationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    long countByExample(MenuOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    int insert(MenuOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    int insertSelective(MenuOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    List<MenuOperation> selectByExample(MenuOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    MenuOperation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MenuOperation record, @Param("example") MenuOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MenuOperation record, @Param("example") MenuOperationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuOperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menuoperation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuOperation record);
}