package cn.xtits.xtp.mapper;

import cn.xtits.xtp.entity.Organize;
import cn.xtits.xtp.entity.OrganizeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface OrganizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    long countByExample(OrganizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    int insert(Organize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    int insertSelective(Organize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    List<Organize> selectByExample(OrganizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    Organize selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Organize record, @Param("example") OrganizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Organize record, @Param("example") OrganizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Organize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organize
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Organize record);
}