package cn.xtits.xtp.mapper;

import cn.xtits.xtp.entity.RoleDataRule;
import cn.xtits.xtp.entity.RoleDataRuleExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoleDataRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    long countByExample(RoleDataRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    int insert(RoleDataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    int insertSelective(RoleDataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    List<RoleDataRule> selectByExample(RoleDataRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    RoleDataRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RoleDataRule record, @Param("example") RoleDataRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RoleDataRule record, @Param("example") RoleDataRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RoleDataRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roledatarule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RoleDataRule record);
}