package cn.xtits.xtp.mapper;

import cn.xtits.xtp.entity.UserFavorite;
import cn.xtits.xtp.entity.UserFavoriteExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    long countByExample(UserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    int insert(UserFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    int insertSelective(UserFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    List<UserFavorite> selectByExample(UserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    UserFavorite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserFavorite record, @Param("example") UserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserFavorite record, @Param("example") UserFavoriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userfavorite
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserFavorite record);
}