package cn.xtits.xtp.mapper;

import cn.xtits.xtp.entity.UserMenu;
import cn.xtits.xtp.entity.UserMenuExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    long countByExample(UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    int insert(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    int insertSelective(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    List<UserMenu> selectByExample(UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    UserMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserMenu record, @Param("example") UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserMenu record, @Param("example") UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usermenu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserMenu record);
}